[package]
name = "near-contract-standards"
version = "4.0.0-pre.2"
authors = ["Near Inc <hello@near.org>"]
edition = "2018"
license = "GPL-3.0"
categories = ["wasm"]
repository = "https://github.com/near/near-sdk-rs"
homepage = "https://github.com/near/near-sdk-rs/tree/master/near-contract-standards"
description = """
NEAR smart contracts standard library.
"""

[dependencies]
near-sdk = { path = "../near-sdk", version = "=4.0.0-pre.2" }
serde = {version = "1.0", features = ["derive"]}
serde_json = {version = "1.0"}
